// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"account-service/internal/biz"
	"account-service/internal/conf"
	"account-service/internal/data"
	"account-service/internal/server"
	"account-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	client "account-service/internal/client"
	"fmt"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}

	customerClient, err := client.NewCustomerClient("localhost:9000") // or use confData
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create account client: %w", err)
	}
	accountcustomerClient, err := client.NewAccountCustomerClient("localhost:9030") // or use confData
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create account client: %w", err)
	}

	greeterRepo := data.NewAccountRepo(dataData, logger)
	greeterUsecase := biz.NewAccountUsecase(greeterRepo, logger)
	greeterService := service.NewAccountService(greeterUsecase,customerClient,accountcustomerClient)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
