// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/account.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CreateRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRequest) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *CreateRequest) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *CreateRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *CreateRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type CreateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CreateResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateResponse) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *CreateResponse) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *CreateResponse) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *CreateResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type UpdateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *UpdateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRequest) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *UpdateRequest) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *UpdateRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *UpdateRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type UpdateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *UpdateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateResponse) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *UpdateResponse) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *UpdateResponse) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *UpdateResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType   string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	CustomerId    string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *DeleteRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *DeleteRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type DeleteResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *DeleteResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *DeleteResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DeleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteResponse) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *DeleteResponse) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *DeleteResponse) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *DeleteResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type FindRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *FindRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *FindRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindRequest) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *FindRequest) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *FindRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *FindRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type FindResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *FindResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *FindResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindResponse) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *FindResponse) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *FindResponse) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *FindResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

var File_api_helloworld_v1_account_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/account.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xbf\x02\n" +
	"\rcreateRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xc0\x02\n" +
	"\x0ecreateResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xbf\x02\n" +
	"\rupdateRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xc0\x02\n" +
	"\x0eupdateResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\x95\x01\n" +
	"\rdeleteRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xc0\x02\n" +
	"\x0edeleteResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xbd\x02\n" +
	"\vfindRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xbe\x02\n" +
	"\ffindResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId2\xaa\x03\n" +
	"\aAccount\x12b\n" +
	"\rCreateAccount\x12\x1c.helloworld.v1.createRequest\x1a\x1d.helloworld.v1.createResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\tv1/create\x12b\n" +
	"\rUpdateAccount\x12\x1c.helloworld.v1.updateRequest\x1a\x1d.helloworld.v1.updateResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\tv1/update\x12r\n" +
	"\rDeleteAccount\x12\x1c.helloworld.v1.deleteRequest\x1a\x1d.helloworld.v1.deleteResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01**\x19v1/delete/{accountNumber}\x12c\n" +
	"\vFindAccount\x12\x1a.helloworld.v1.findRequest\x1a\x1b.helloworld.v1.findResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13v1/find/{accountId}Bg\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z2account-service/api/helloworld/v1/account.proto;v1b\x06proto3"

var (
	file_api_helloworld_v1_account_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_account_proto_rawDescData []byte
)

func file_api_helloworld_v1_account_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_account_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_account_proto_rawDesc), len(file_api_helloworld_v1_account_proto_rawDesc)))
	})
	return file_api_helloworld_v1_account_proto_rawDescData
}

var file_api_helloworld_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_helloworld_v1_account_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: helloworld.v1.createRequest
	(*CreateResponse)(nil), // 1: helloworld.v1.createResponse
	(*UpdateRequest)(nil),  // 2: helloworld.v1.updateRequest
	(*UpdateResponse)(nil), // 3: helloworld.v1.updateResponse
	(*DeleteRequest)(nil),  // 4: helloworld.v1.deleteRequest
	(*DeleteResponse)(nil), // 5: helloworld.v1.deleteResponse
	(*FindRequest)(nil),    // 6: helloworld.v1.findRequest
	(*FindResponse)(nil),   // 7: helloworld.v1.findResponse
}
var file_api_helloworld_v1_account_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Account.CreateAccount:input_type -> helloworld.v1.createRequest
	2, // 1: helloworld.v1.Account.UpdateAccount:input_type -> helloworld.v1.updateRequest
	4, // 2: helloworld.v1.Account.DeleteAccount:input_type -> helloworld.v1.deleteRequest
	6, // 3: helloworld.v1.Account.FindAccount:input_type -> helloworld.v1.findRequest
	1, // 4: helloworld.v1.Account.CreateAccount:output_type -> helloworld.v1.createResponse
	3, // 5: helloworld.v1.Account.UpdateAccount:output_type -> helloworld.v1.updateResponse
	5, // 6: helloworld.v1.Account.DeleteAccount:output_type -> helloworld.v1.deleteResponse
	7, // 7: helloworld.v1.Account.FindAccount:output_type -> helloworld.v1.findResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_account_proto_init() }
func file_api_helloworld_v1_account_proto_init() {
	if File_api_helloworld_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_account_proto_rawDesc), len(file_api_helloworld_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_account_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_account_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_account_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_account_proto = out.File
	file_api_helloworld_v1_account_proto_goTypes = nil
	file_api_helloworld_v1_account_proto_depIdxs = nil
}
