// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/account.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account1) Reset() {
	*x = Account1{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account1) ProtoMessage() {}

func (x *Account1) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account1.ProtoReflect.Descriptor instead.
func (*Account1) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account1) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Account1) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *Account1) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account1) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account1) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *Account1) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *Account1) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *Account1) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type CreateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CreateRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateRequest) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *CreateRequest) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *CreateRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *CreateRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type CreateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Message          string                 `protobuf:"bytes,10,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *CreateResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateResponse) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *CreateResponse) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *CreateResponse) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *CreateResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *UpdateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRequest) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *UpdateRequest) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *UpdateRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *UpdateRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type UpdateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Message          string                 `protobuf:"bytes,10,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *UpdateResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *UpdateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateResponse) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *UpdateResponse) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *UpdateResponse) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *UpdateResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType   string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	CustomerId    string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *DeleteRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *DeleteRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *FindRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindRequest) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *FindRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindRequest) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *FindRequest) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *FindRequest) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *FindRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type FindResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Message          string                 `protobuf:"bytes,10,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindResponse) Reset() {
	*x = FindResponse{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse) ProtoMessage() {}

func (x *FindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse.ProtoReflect.Descriptor instead.
func (*FindResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *FindResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindResponse) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *FindResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindResponse) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *FindResponse) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *FindResponse) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *FindResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *FindResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindRequest1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest1) Reset() {
	*x = FindRequest1{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest1) ProtoMessage() {}

func (x *FindRequest1) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest1.ProtoReflect.Descriptor instead.
func (*FindRequest1) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *FindRequest1) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type FindResponse2 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Message          string                 `protobuf:"bytes,10,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindResponse2) Reset() {
	*x = FindResponse2{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse2) ProtoMessage() {}

func (x *FindResponse2) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse2.ProtoReflect.Descriptor instead.
func (*FindResponse2) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{10}
}

func (x *FindResponse2) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindResponse2) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindResponse2) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *FindResponse2) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindResponse2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindResponse2) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *FindResponse2) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *FindResponse2) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *FindResponse2) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *FindResponse2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindResponse1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        int64                  `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountNumber    int64                  `protobuf:"varint,2,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,6,opt,name=availableBalance,proto3" json:"availableBalance,omitempty"`
	PendingBalance   string                 `protobuf:"bytes,7,opt,name=pendingBalance,proto3" json:"pendingBalance,omitempty"`
	CreditLimit      string                 `protobuf:"bytes,8,opt,name=creditLimit,proto3" json:"creditLimit,omitempty"`
	CustomerId       string                 `protobuf:"bytes,9,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Message          string                 `protobuf:"bytes,11,opt,name=Message,proto3" json:"Message,omitempty"`
	Account          []*Account1            `protobuf:"bytes,10,rep,name=account,proto3" json:"account,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindResponse1) Reset() {
	*x = FindResponse1{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindResponse1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindResponse1) ProtoMessage() {}

func (x *FindResponse1) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindResponse1.ProtoReflect.Descriptor instead.
func (*FindResponse1) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *FindResponse1) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FindResponse1) GetAccountNumber() int64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FindResponse1) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *FindResponse1) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FindResponse1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FindResponse1) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *FindResponse1) GetPendingBalance() string {
	if x != nil {
		return x.PendingBalance
	}
	return ""
}

func (x *FindResponse1) GetCreditLimit() string {
	if x != nil {
		return x.CreditLimit
	}
	return ""
}

func (x *FindResponse1) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *FindResponse1) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FindResponse1) GetAccount() []*Account1 {
	if x != nil {
		return x.Account
	}
	return nil
}

type Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resp) Reset() {
	*x = Resp{}
	mi := &file_api_helloworld_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_account_proto_rawDescGZIP(), []int{12}
}

func (x *Resp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_helloworld_v1_account_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/account.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\xba\x02\n" +
	"\bAccount1\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xbf\x02\n" +
	"\rcreateRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xda\x02\n" +
	"\x0ecreateResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\x12\x18\n" +
	"\aMessage\x18\n" +
	" \x01(\tR\aMessage\"\xbf\x02\n" +
	"\rupdateRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xda\x02\n" +
	"\x0eupdateResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\x12\x18\n" +
	"\aMessage\x18\n" +
	" \x01(\tR\aMessage\"\x95\x01\n" +
	"\rdeleteRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"*\n" +
	"\x0edeleteResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\"\xbd\x02\n" +
	"\vfindRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xd8\x02\n" +
	"\ffindResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\x12\x18\n" +
	"\aMessage\x18\n" +
	" \x01(\tR\aMessage\".\n" +
	"\ffindRequest1\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\"\xd9\x02\n" +
	"\rfindResponse2\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\x12\x18\n" +
	"\aMessage\x18\n" +
	" \x01(\tR\aMessage\"\x8c\x03\n" +
	"\rfindResponse1\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\x03R\taccountId\x12$\n" +
	"\raccountNumber\x18\x02 \x01(\x03R\raccountNumber\x12 \n" +
	"\vaccountType\x18\x03 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12*\n" +
	"\x10availableBalance\x18\x06 \x01(\tR\x10availableBalance\x12&\n" +
	"\x0ependingBalance\x18\a \x01(\tR\x0ependingBalance\x12 \n" +
	"\vcreditLimit\x18\b \x01(\tR\vcreditLimit\x12\x1e\n" +
	"\n" +
	"customerId\x18\t \x01(\tR\n" +
	"customerId\x12\x18\n" +
	"\aMessage\x18\v \x01(\tR\aMessage\x121\n" +
	"\aaccount\x18\n" +
	" \x03(\v2\x17.helloworld.v1.Account1R\aaccount\" \n" +
	"\x04resp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xaf\x05\n" +
	"\aAccount\x12j\n" +
	"\rCreateAccount\x12\x1c.helloworld.v1.createRequest\x1a\x1d.helloworld.v1.createResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11v1/account/create\x12j\n" +
	"\rUpdateAccount\x12\x1c.helloworld.v1.updateRequest\x1a\x1d.helloworld.v1.updateResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11v1/account/update\x12j\n" +
	"\rDeleteAccount\x12\x1c.helloworld.v1.deleteRequest\x1a\x1d.helloworld.v1.deleteResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01**\x11v1/account/delete\x12k\n" +
	"\vFindAccount\x12\x1a.helloworld.v1.findRequest\x1a\x1b.helloworld.v1.findResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1bv1/account/find/{accountId}\x12{\n" +
	"\x11FindAccountNumber\x12\x1a.helloworld.v1.findRequest\x1a\x1b.helloworld.v1.findResponse\"-\x82\xd3\xe4\x93\x02'\x12%v1/accountnumber/find/{accountNumber}\x12v\n" +
	"\x10FindByCustomerId\x12\x1b.helloworld.v1.findRequest1\x1a\x1c.helloworld.v1.findResponse2\"'\x82\xd3\xe4\x93\x02!\x12\x1fv1/customerId/find/{customerId}Bg\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z2account-service/api/helloworld/v1/account.proto;v1b\x06proto3"

var (
	file_api_helloworld_v1_account_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_account_proto_rawDescData []byte
)

func file_api_helloworld_v1_account_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_account_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_account_proto_rawDesc), len(file_api_helloworld_v1_account_proto_rawDesc)))
	})
	return file_api_helloworld_v1_account_proto_rawDescData
}

var file_api_helloworld_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_helloworld_v1_account_proto_goTypes = []any{
	(*Account1)(nil),       // 0: helloworld.v1.Account1
	(*CreateRequest)(nil),  // 1: helloworld.v1.createRequest
	(*CreateResponse)(nil), // 2: helloworld.v1.createResponse
	(*UpdateRequest)(nil),  // 3: helloworld.v1.updateRequest
	(*UpdateResponse)(nil), // 4: helloworld.v1.updateResponse
	(*DeleteRequest)(nil),  // 5: helloworld.v1.deleteRequest
	(*DeleteResponse)(nil), // 6: helloworld.v1.deleteResponse
	(*FindRequest)(nil),    // 7: helloworld.v1.findRequest
	(*FindResponse)(nil),   // 8: helloworld.v1.findResponse
	(*FindRequest1)(nil),   // 9: helloworld.v1.findRequest1
	(*FindResponse2)(nil),  // 10: helloworld.v1.findResponse2
	(*FindResponse1)(nil),  // 11: helloworld.v1.findResponse1
	(*Resp)(nil),           // 12: helloworld.v1.resp
}
var file_api_helloworld_v1_account_proto_depIdxs = []int32{
	0,  // 0: helloworld.v1.findResponse1.account:type_name -> helloworld.v1.Account1
	1,  // 1: helloworld.v1.Account.CreateAccount:input_type -> helloworld.v1.createRequest
	3,  // 2: helloworld.v1.Account.UpdateAccount:input_type -> helloworld.v1.updateRequest
	5,  // 3: helloworld.v1.Account.DeleteAccount:input_type -> helloworld.v1.deleteRequest
	7,  // 4: helloworld.v1.Account.FindAccount:input_type -> helloworld.v1.findRequest
	7,  // 5: helloworld.v1.Account.FindAccountNumber:input_type -> helloworld.v1.findRequest
	9,  // 6: helloworld.v1.Account.FindByCustomerId:input_type -> helloworld.v1.findRequest1
	2,  // 7: helloworld.v1.Account.CreateAccount:output_type -> helloworld.v1.createResponse
	4,  // 8: helloworld.v1.Account.UpdateAccount:output_type -> helloworld.v1.updateResponse
	6,  // 9: helloworld.v1.Account.DeleteAccount:output_type -> helloworld.v1.deleteResponse
	8,  // 10: helloworld.v1.Account.FindAccount:output_type -> helloworld.v1.findResponse
	8,  // 11: helloworld.v1.Account.FindAccountNumber:output_type -> helloworld.v1.findResponse
	10, // 12: helloworld.v1.Account.FindByCustomerId:output_type -> helloworld.v1.findResponse2
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_account_proto_init() }
func file_api_helloworld_v1_account_proto_init() {
	if File_api_helloworld_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_account_proto_rawDesc), len(file_api_helloworld_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_account_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_account_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_account_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_account_proto = out.File
	file_api_helloworld_v1_account_proto_goTypes = nil
	file_api_helloworld_v1_account_proto_depIdxs = nil
}
